const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, '..', 'src', 'data', 'conteudo.json');
const d = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const novasQuestoes = [
  // ---- SUS (q017-q034) ----
  {id:'q017',temaId:'sus',categoria:'geral',enunciado:'A Constituição Federal de 1988, em seu artigo 196, define saúde como:',alternativas:['a) Ausência de doenças e enfermidades','b) Direito de todos e dever do Estado, garantido mediante políticas sociais e econômicas que visem à redução do risco de doença e ao acesso universal e igualitário','c) Responsabilidade exclusiva do Ministério da Saúde e das secretarias estaduais','d) Serviço público prestado mediante contribuição previdenciária ao INAMPS','e) Conjunto de ações de promoção e prevenção de agravos, excluindo a recuperação'],correta:1,explicacao:'Art. 196 CF/1988: saúde é direito de todos e dever do Estado, garantido por políticas sociais e econômicas voltadas à redução do risco de doença e ao acesso universal e igualitário às ações e serviços de promoção, proteção e recuperação.',dificuldade:'facil',origem:'seed'},
  {id:'q018',temaId:'sus',categoria:'geral',enunciado:'Qual das leis abaixo é denominada Lei Orgânica da Saúde e dispõe sobre as condições para promoção, proteção e recuperação da saúde, bem como sobre a organização e funcionamento do SUS?',alternativas:['a) Lei 8.142/1990','b) Lei 9.313/1996','c) Lei 8.080/1990','d) Lei 9.782/1999','e) Decreto-Lei 986/1969'],correta:2,explicacao:'A Lei 8.080/1990 é a Lei Orgânica da Saúde. A Lei 8.142/1990 complementa-a tratando da participação comunitária e das transferências intergovernamentais de recursos.',dificuldade:'facil',origem:'seed'},
  {id:'q019',temaId:'sus',categoria:'geral',enunciado:'O princípio do SUS que garante que toda pessoa tem direito ao acesso às ações e serviços de saúde, sem qualquer discriminação, é denominado:',alternativas:['a) Integralidade','b) Equidade','c) Universalidade','d) Descentralização','e) Hierarquização'],correta:2,explicacao:'Universalidade garante o acesso de todos às ações e serviços de saúde, sem discriminação. Integralidade refere-se ao conjunto de ações. Equidade trata de priorizar quem mais precisa.',dificuldade:'facil',origem:'seed'},
  {id:'q020',temaId:'sus',categoria:'geral',enunciado:'Segundo a Lei 8.142/1990, os Conselhos de Saúde são órgãos:',alternativas:['a) Deliberativos, consultivos e de execução direta de políticas de saúde','b) Apenas consultivos, vinculados ao Ministério da Saúde','c) De caráter permanente e deliberativo, com composição paritária: 50% de usuários e 50% dos demais segmentos','d) Fiscalizadores, compostos exclusivamente por usuários dos serviços de saúde','e) Consultivos, presididos obrigatoriamente pelo titular da pasta de saúde'],correta:2,explicacao:'Lei 8.142/1990 — Conselhos de Saúde são órgãos de caráter permanente e deliberativo, com composição paritária: 50% de representantes de usuários e 50% de governo, prestadores e profissionais de saúde.',dificuldade:'facil',origem:'seed'},
  {id:'q021',temaId:'sus',categoria:'geral',enunciado:'O financiamento do SUS é responsabilidade:',alternativas:['a) Exclusiva da União Federal','b) Exclusiva dos municípios, como gestores da atenção básica','c) Compartilhada entre União, estados e municípios (financiamento tripartite)','d) Exclusiva dos estados, que repassam aos municípios','e) Da União e dos estados, cabendo aos municípios apenas a gestão operacional'],correta:2,explicacao:'O financiamento do SUS é tripartite: responsabilidade compartilhada entre as três esferas de governo — União, estados e municípios. A LC 141/2012 define os percentuais mínimos de cada ente.',dificuldade:'facil',origem:'seed'},
  {id:'q022',temaId:'sus',categoria:'geral',enunciado:'A RENAME, instituída pelo Decreto 7.508/2011, corresponde à:',alternativas:['a) Relação Nacional de Medicamentos Essenciais','b) Rede Nacional de Atenção em Emergências','c) Registro Nacional de Estabelecimentos e Medicamentos','d) Relação Nacional de Ações e Serviços de Saúde','e) Rede de Atenção às Urgências e Emergências do SUS'],correta:0,explicacao:'RENAME = Relação Nacional de Medicamentos Essenciais — lista de medicamentos disponíveis no SUS, institucionalizada pelo Decreto 7.508/2011. Não confundir com RENASES (Relação Nacional de Ações e Serviços de Saúde).',dificuldade:'facil',origem:'seed'},
  {id:'q023',temaId:'sus',categoria:'geral',enunciado:'Segundo a Lei 8.142/1990, a periodicidade ordinária de reunião das Conferências de Saúde é de:',alternativas:['a) 1 ano','b) 2 anos','c) 3 anos','d) 4 anos','e) 5 anos'],correta:3,explicacao:'Lei 8.142/1990, art. 1°, §1°: a Conferência de Saúde reunir-se-á a cada quatro anos, com representação dos vários segmentos sociais, para avaliar a situação de saúde e propor diretrizes para a formulação de políticas.',dificuldade:'facil',origem:'seed'},
  {id:'q024',temaId:'sus',categoria:'geral',enunciado:'Segundo a Lei 8.080/1990, são fatores determinantes e condicionantes da saúde, EXCETO:',alternativas:['a) Alimentação e moradia','b) Saneamento básico e meio ambiente','c) Renda e nível de educação','d) Trabalho e transporte','e) Disponibilidade de leitos hospitalares na região'],correta:4,explicacao:'Art. 3° da Lei 8.080/1990 lista como determinantes: alimentação, moradia, saneamento, meio ambiente, trabalho, renda, educação, transporte, lazer e acesso a bens essenciais. Leitos hospitalares são recursos do sistema, não determinantes da saúde.',dificuldade:'media',origem:'seed'},
  {id:'q025',temaId:'sus',categoria:'geral',enunciado:'A Lei Complementar 141/2012, ao regulamentar a Emenda Constitucional 29/2000, estabelece principalmente:',alternativas:['a) A criação de novos hospitais universitários federais','b) Os valores mínimos a serem aplicados anualmente em saúde por cada ente federativo e o que pode ser computado como despesa de saúde','c) O financiamento exclusivo da Atenção Básica pelo governo federal via PAB fixo','d) O repasse de recursos do SUS para organizações sociais de saúde','e) A criação do Fundo Nacional de Saúde como único mecanismo de transferência'],correta:1,explicacao:'A LC 141/2012 regulamenta a EC 29/2000 fixando percentuais mínimos: União (15% da RCL), estados (12% da receita própria) e municípios (15% da receita própria). Define também o que pode ser computado como gasto em saúde.',dificuldade:'media',origem:'seed'},
  {id:'q026',temaId:'sus',categoria:'geral',enunciado:'O Decreto 7.508/2011, ao regulamentar a Lei 8.080/1990, define como "portas de entrada" do SUS os serviços de:',alternativas:['a) Referência para procedimentos de alta e média complexidade exclusivamente','b) Atenção básica, atenção de urgência e emergência, atenção psicossocial e serviços especiais de acesso aberto','c) Pronto-socorro e prontos-atendimentos de hospitais gerais','d) Diagnóstico especializado habilitados pelo Ministério da Saúde','e) Hospitais gerais de médio e grande porte com leitos SUS habilitados'],correta:1,explicacao:'Art. 9° do Decreto 7.508/2011: são portas de entrada do SUS os serviços de atenção básica, de atenção de urgência e emergência, de atenção psicossocial, e os serviços especiais de acesso aberto.',dificuldade:'media',origem:'seed'},
  {id:'q027',temaId:'sus',categoria:'geral',enunciado:'O princípio da equidade no SUS pressupõe que:',alternativas:['a) Todos os cidadãos devem receber exatamente os mesmos serviços de saúde, sem qualquer distinção','b) Os serviços devem ser gratuitos para a população de baixa renda e pagos para os demais','c) Devem ser reduzidas as diferenças injustas e evitáveis, priorizando aqueles com maior necessidade de saúde','d) A distribuição de recursos deve ser estritamente igual entre todas as regiões do país','e) O acesso aos serviços especializados deve ser livre, sem necessidade de referenciamento'],correta:2,explicacao:'Equidade não é igualdade aritmética: significa tratar desigualmente os desiguais, alocando mais recursos e atenção onde a necessidade é maior, com o objetivo de reduzir desigualdades sociais e de saúde.',dificuldade:'media',origem:'seed'},
  {id:'q028',temaId:'sus',categoria:'geral',enunciado:'Segundo a Lei 8.142/1990, a Conferência de Saúde pode ser convocada extraordinariamente pelo:',alternativas:['a) Ministro da Saúde, por decreto presidencial','b) Conselho de Saúde, independentemente do Poder Executivo','c) Procurador-Geral da República, mediante representação do CNS','d) Presidente do Conselho Nacional de Saúde com aprovação de 2/3 dos membros','e) Tribunal de Contas da União, em caso de irregularidades'],correta:1,explicacao:'Lei 8.142/1990, art. 1°, §3°: a Conferência de Saúde será convocada pelo Poder Executivo ordinariamente ou, extraordinariamente, pelo Conselho de Saúde.',dificuldade:'media',origem:'seed'},
  {id:'q029',temaId:'sus',categoria:'geral',enunciado:'A Norma Operacional Básica SUS 01/96 (NOB-SUS 96) introduziu, para os municípios, os seguintes tipos de habilitação:',alternativas:['a) Gestão Plena da Atenção Básica e Gestão Plena do Sistema Municipal','b) Gestão Incipiente, Gestão Parcial e Gestão Semiplena','c) Gestão Básica e Gestão Ampliada de Serviços de Saúde','d) Gestão Estadual Ampliada e Gestão Municipal Básica','e) Gestão por Resultados e Gestão por Processos Assistenciais'],correta:0,explicacao:'A NOB-SUS 01/96 definiu as habilitações municipais em Gestão Plena da Atenção Básica (GPAB) e Gestão Plena do Sistema Municipal (GPSM), substituindo os modelos da NOB 01/93 (incipiente, parcial, semiplena).',dificuldade:'media',origem:'seed'},
  {id:'q030',temaId:'sus',categoria:'geral',enunciado:'A RENASES, instituída pelo Decreto 7.508/2011, define:',alternativas:['a) Todos os medicamentos disponíveis na rede pública de saúde federal','b) As ações e serviços que o SUS oferece ao usuário para atendimento integral à sua saúde','c) A lista de equipamentos e insumos estratégicos para saúde pública','d) A relação de estabelecimentos de saúde credenciados ao SUS por estado','e) As ações de vigilância sanitária prestadas exclusivamente pela ANVISA'],correta:1,explicacao:'RENASES = Relação Nacional de Ações e Serviços de Saúde — compreende todas as ações e serviços que o SUS oferece ao usuário para atendimento integral à sua saúde, definida e publicada pelo Ministério da Saúde.',dificuldade:'media',origem:'seed'},
  {id:'q031',temaId:'sus',categoria:'geral',enunciado:'Conforme a Lei 8.142/1990, para que municípios recebam transferências intergovernamentais de recursos do SUS, é DESNECESSÁRIO possuir:',alternativas:['a) Fundo de Saúde','b) Conselho de Saúde em funcionamento','c) Plano de Saúde','d) Relatórios de Gestão que permitam o controle','e) Hospital geral com pelo menos 30 leitos SUS habilitados'],correta:4,explicacao:'Lei 8.142/1990, art. 4°: as condições para recebimento de recursos são: Fundo de Saúde, Conselho de Saúde, Plano de Saúde, Relatórios de Gestão, contrapartida de recursos e Comissão de Auditoria. Não há exigência de hospital geral.',dificuldade:'dificil',origem:'seed'},
  {id:'q032',temaId:'sus',categoria:'geral',enunciado:'O Pacto pela Saúde, instituído pela Portaria GM/MS 399/2006, foi composto por três componentes, que são:',alternativas:['a) Pacto pela Vida, Pacto em Defesa do SUS e Pacto de Gestão do SUS','b) Pacto pela Equidade, Pacto pela Integralidade e Pacto de Gestão','c) Pacto pela Atenção Básica, Pacto pela Média Complexidade e Pacto de Gestão','d) Pacto pela Vida, Pacto pela Equidade e Pacto pela Descentralização','e) Pacto de Solidariedade, Pacto de Gestão e Pacto em Defesa do SUS'],correta:0,explicacao:'A Portaria GM/MS 399/2006 instituiu o Pacto pela Saúde 2006, composto por: 1) Pacto pela Vida (metas assistenciais prioritárias), 2) Pacto em Defesa do SUS (ampliação do financiamento), 3) Pacto de Gestão do SUS (responsabilidades entre esferas).',dificuldade:'dificil',origem:'seed'},
  {id:'q033',temaId:'sus',categoria:'geral',enunciado:'Segundo a Lei 8.080/1990, a direção do SUS é exercida, em cada esfera de governo, por:',alternativas:['a) Comitê gestor tripartite formado por União, estado e município','b) Ministério da Saúde (federal), Secretarias Estaduais de Saúde (estadual) e Secretarias Municipais de Saúde (municipal)','c) Conselhos de Saúde em parceria com as respectivas secretarias de saúde','d) ANVISA, ANS e demais agências reguladoras em suas competências','e) Conselho Nacional de Saúde como órgão máximo do SUS'],correta:1,explicacao:'Lei 8.080/1990, art. 9°: a direção do SUS é única em cada esfera de governo, exercida pelo Ministério da Saúde (federal), Secretaria de Saúde Estadual/DF (estadual) e Secretaria de Saúde Municipal (municipal).',dificuldade:'dificil',origem:'seed'},
  {id:'q034',temaId:'sus',categoria:'geral',enunciado:'A Comissão Intergestores Tripartite (CIT) é composta por representantes de:',alternativas:['a) União, estados e municípios, com paridade entre as três esferas','b) Ministério da Saúde, Conselho Nacional de Saúde e Conselho Federal de Medicina','c) CONASS, CONASEMS e Ministério da Saúde','d) Municípios, estados e Conselho Nacional de Saúde','e) União, Conselho Nacional de Saúde e representantes de prestadores privados'],correta:2,explicacao:'A CIT reúne: Ministério da Saúde (representando a União), CONASS (Conselho Nacional de Secretários de Saúde, representando os estados) e CONASEMS (Conselho Nacional de Secretarias Municipais de Saúde). É o fórum de negociação e pactuação tripartite.',dificuldade:'dificil',origem:'seed'},

  // ---- politicas-saude (q035-q054) ----
  {id:'q035',temaId:'politicas-saude',categoria:'geral',enunciado:'A 8ª Conferência Nacional de Saúde, realizada em 1986, ficou historicamente marcada por:',alternativas:['a) Criar o INAMPS como modelo de saúde previdenciário unificado','b) Propor uma reforma sanitária com conceito ampliado de saúde, base da criação do SUS na CF/1988','c) Regulamentar definitivamente a participação privada nos serviços de saúde','d) Estabelecer as primeiras diretrizes da Atenção Básica no Brasil','e) Criar o Conselho Nacional de Saúde como órgão deliberativo paritário'],correta:1,explicacao:'A 8ª CNS (1986) foi o marco da Reforma Sanitária brasileira, com ampla participação popular. Propôs o conceito ampliado de saúde, o controle social e um sistema universal, único e equânime — fundamentos do SUS na CF/1988.',dificuldade:'facil',origem:'seed'},
  {id:'q036',temaId:'politicas-saude',categoria:'geral',enunciado:'O modelo de saúde brasileiro anterior ao SUS (pré-1988) era caracterizado pela divisão entre:',alternativas:['a) Saúde pública (Ministério da Saúde) e medicina previdenciária (INAMPS/MPAS) para contribuintes','b) Saúde pública e saúde suplementar já regulada pela ANS','c) Atenção primária de responsabilidade municipal e atenção hospitalar estadual','d) SUS e SUDS como sistemas paralelos e complementares','e) FUNRURAL e INPS como únicos prestadores de serviços de saúde no país'],correta:0,explicacao:'Antes do SUS o sistema era segmentado: o Ministério da Saúde respondia pela saúde pública (vacinações, vigilância) e o INAMPS (vinculado ao Ministério da Previdência) prestava assistência médica apenas aos trabalhadores com carteira assinada.',dificuldade:'facil',origem:'seed'},
  {id:'q037',temaId:'politicas-saude',categoria:'geral',enunciado:'Segundo Paim et al. (The Lancet, 2011), um dos principais avanços do SUS desde sua criação foi:',alternativas:['a) A eliminação completa das desigualdades regionais em saúde','b) A expansão da Estratégia Saúde da Família e a eficácia dos programas nacionais de imunização','c) A extinção do setor suplementar privado de saúde','d) O gasto público em saúde que passou a superar 70% do total gasto no país','e) A judicialização zero das políticas de saúde pelo Poder Judiciário'],correta:1,explicacao:'Paim et al. destacam como avanços: expansão da ESF/APS, resultados dos programas de imunização (cobertura ampla), programa nacional de HIV/AIDS (referência mundial) e ampliação do acesso. Os desafios incluem subfinanciamento e segmentação.',dificuldade:'facil',origem:'seed'},
  {id:'q038',temaId:'politicas-saude',categoria:'geral',enunciado:'A Estratégia Saúde da Família (ESF) foi implantada no Brasil a partir de:',alternativas:['a) 1988, junto com a criação do SUS pela CF/1988','b) 1994, como evolução do Programa de Agentes Comunitários de Saúde (PACS/1991)','c) 2001, após a NOAS-SUS 01/2001 ampliar as responsabilidades municipais','d) 2006, com a publicação do Pacto pela Saúde','e) 2012, como parte da nova Política Nacional de Atenção Básica'],correta:1,explicacao:'A ESF foi criada em 1994, como evolução do PACS (1991). Representou a reorientação do modelo assistencial com foco na APS, território adscrito, família e equipe multiprofissional (médico, enfermeiro, técnico de enfermagem, ACS).',dificuldade:'facil',origem:'seed'},
  {id:'q039',temaId:'politicas-saude',categoria:'geral',enunciado:'A regulação dos planos e seguros privados de saúde (saúde suplementar) no Brasil é responsabilidade da:',alternativas:['a) ANVISA (Agência Nacional de Vigilância Sanitária)','b) ANS (Agência Nacional de Saúde Suplementar)','c) Conselho Federal de Medicina','d) Secretaria de Vigilância em Saúde do Ministério da Saúde','e) Ministério da Previdência Social'],correta:1,explicacao:'A ANS foi criada pela Lei 9.961/2000 com a função de regular os planos e seguros privados de saúde no Brasil, garantindo os direitos dos beneficiários e regulando coberturas, carências e mensalidades.',dificuldade:'facil',origem:'seed'},
  {id:'q040',temaId:'politicas-saude',categoria:'geral',enunciado:'O conceito ampliado de saúde, adotado pelo SUS e pela 8ª CNS, define saúde como:',alternativas:['a) Ausência de doenças físicas diagnosticáveis por exames laboratoriais','b) Resultante das condições de vida e trabalho — alimentação, moradia, renda, educação, ambiente e acesso a serviços','c) Responsabilidade exclusiva dos profissionais da área médica e de enfermagem','d) Estado de completo bem-estar físico, mental e social, independente de condições socioeconômicas','e) Indicador mensurado apenas pelas taxas de mortalidade infantil e materna'],correta:1,explicacao:'O conceito ampliado vai além da ausência de doença: saúde é resultado das condições de vida e trabalho, incluindo determinantes sociais (renda, educação, moradia, saneamento). Fundamentou o SUS como política de estado integrada a outras políticas sociais.',dificuldade:'facil',origem:'seed'},
  {id:'q041',temaId:'politicas-saude',categoria:'geral',enunciado:'O Programa de Agentes Comunitários de Saúde (PACS) foi criado em:',alternativas:['a) 1978, como resultado da Declaração de Alma-Ata','b) 1988, juntamente com a criação do SUS na CF/1988','c) 1991, como estratégia de extensão da cobertura em saúde nas regiões Norte e Nordeste','d) 1994, vinculado ao lançamento da Estratégia Saúde da Família','e) 2000, como parte da Política Nacional de Atenção Básica'],correta:2,explicacao:'O PACS foi criado em 1991, inicialmente nas Regiões Nordeste e Amazônica, com foco na redução da mortalidade infantil e materna por meio de visitas domiciliares de agentes comunitários. Precursor e base da ESF (1994).',dificuldade:'facil',origem:'seed'},
  {id:'q042',temaId:'politicas-saude',categoria:'geral',enunciado:'Qual evento internacional, realizado em 1978, estabeleceu os princípios de Atenção Primária à Saúde e influenciou fortemente o movimento da Reforma Sanitária brasileira?',alternativas:['a) 1ª Conferência Internacional sobre Promoção da Saúde — Carta de Ottawa (1986)','b) Conferência Internacional sobre Cuidados Primários de Saúde — Declaração de Alma-Ata (1978)','c) Conferência de Astana sobre Atenção Primária (2018)','d) Declaração do Milênio das Nações Unidas (2000)','e) Relatório Dawson sobre organização dos serviços de saúde (1920)'],correta:1,explicacao:'A Declaração de Alma-Ata (1978, URSS/OMS/UNICEF) propôs a estratégia "Saúde para Todos no Ano 2000" e definiu APS como pilar dos sistemas de saúde. Influenciou diretamente o movimento sanitarista e a criação do SUS.',dificuldade:'facil',origem:'seed'},
  {id:'q043',temaId:'politicas-saude',categoria:'geral',enunciado:'Segundo Paim et al. (The Lancet, 2011), qual é o principal desafio estrutural do sistema de saúde brasileiro?',alternativas:['a) A ausência de serviços de atenção terciária e centros de referência especializados','b) A baixa cobertura vacinal da população infantil e adulta','c) A segmentação entre setor público (SUS) e saúde suplementar privada, associada ao subfinanciamento crônico do SUS','d) A escassez absoluta de recursos humanos qualificados em saúde no país','e) A inexistência de uma política nacional estruturada de atenção básica'],correta:2,explicacao:'Paim et al. identificam como desafio central a segmentação do sistema — SUS universal + suplementar (para quem pode pagar) + subsistema federal — combinada ao subfinanciamento do SUS. Essa dualidade gera desigualdades e disputas por recursos.',dificuldade:'media',origem:'seed'},
  {id:'q044',temaId:'politicas-saude',categoria:'geral',enunciado:'A Reforma Psiquiátrica brasileira, consolidada pela Lei 10.216/2001, preconiza:',alternativas:['a) A internação hospitalar compulsória como primeira e principal opção terapêutica','b) A extinção imediata de todos os hospitais psiquiátricos em prazo de 5 anos','c) A proteção dos direitos das pessoas com transtornos mentais, com prioridade para tratamento em serviços comunitários e internação como último recurso','d) O tratamento exclusivo por psiquiatras em unidades de saúde mental especializadas','e) A criação de leitos psiquiátricos exclusivamente em hospitais gerais de grande porte'],correta:2,explicacao:'A Lei 10.216/2001 (Lei Paulo Delgado) redireciona o modelo assistencial: protege direitos dos pacientes com transtornos mentais, define internação como último recurso após esgotamento dos recursos extra-hospitalares, e prioriza serviços comunitários (CAPS, residências terapêuticas).',dificuldade:'media',origem:'seed'},
  {id:'q045',temaId:'politicas-saude',categoria:'geral',enunciado:'O Programa Nacional de Imunizações (PNI), um dos mais abrangentes do mundo, tem como característica fundamental:',alternativas:['a) Vacinação compulsória e paga exclusivamente para trabalhadores formais contribuintes do INSS','b) Oferta universal, gratuita e igualitária das vacinas do calendário nacional para todos os ciclos de vida','c) Distribuição de vacinas apenas para menores de 5 anos e idosos acima de 65 anos','d) Gestão totalmente descentralizada, com autonomia dos municípios para definir seus próprios calendários','e) Financiamento exclusivo por organismos internacionais como OPAS e UNICEF'],correta:1,explicacao:'O PNI (criado em 1973 e incorporado ao SUS) garante vacinação universal, gratuita e igualitária conforme calendário nacional, abrangendo crianças, adolescentes, adultos, idosos e gestantes. É considerado referência mundial.',dificuldade:'media',origem:'seed'},
  {id:'q046',temaId:'politicas-saude',categoria:'geral',enunciado:'A vigilância epidemiológica, segundo a Lei 8.080/1990, constitui-se em um conjunto de ações que proporciona:',alternativas:['a) O controle sanitário de produtos, serviços e ambientes de interesse à saúde','b) O conhecimento, detecção ou prevenção de qualquer mudança nos fatores determinantes e condicionantes de saúde individual ou coletiva','c) A fiscalização de estabelecimentos de saúde, alimentos e cosméticos','d) A promoção de saúde e prevenção de agravos exclusivamente no âmbito da atenção básica','e) A investigação de crimes e infrações relacionados à saúde pública'],correta:1,explicacao:'Vigilância epidemiológica visa ao conhecimento, detecção ou prevenção de qualquer mudança nos fatores determinantes e condicionantes de saúde individual ou coletiva — subsidiando medidas de prevenção e controle de doenças e agravos.',dificuldade:'media',origem:'seed'},
  {id:'q047',temaId:'politicas-saude',categoria:'geral',enunciado:'O NASF-AB (Núcleo Ampliado de Saúde da Família e Atenção Básica) tem como objetivo principal:',alternativas:['a) Substituir as equipes de Saúde da Família em municípios com menos de 30.000 habitantes','b) Prestar apoio técnico e clínico às equipes de atenção básica por meio do apoio matricial, ampliando a resolubilidade','c) Realizar internações domiciliares de pacientes oriundos das equipes de APS','d) Coordenar as redes de atenção especializada ambulatorial no âmbito municipal','e) Realizar exclusivamente ações coletivas de promoção de saúde e prevenção de doenças'],correta:1,explicacao:'O NASF-AB apoia as equipes de APS (ESF e outros), ampliando a resolubilidade, a abrangência e o escopo das ações por meio de clínica ampliada, apoio matricial e Projeto Terapêutico Singular (PTS), sem substituir as equipes de referência.',dificuldade:'media',origem:'seed'},
  {id:'q048',temaId:'politicas-saude',categoria:'geral',enunciado:'A judicialização da saúde, fenômeno crescente no Brasil pós-SUS destacado por Paim et al. (2011), refere-se principalmente a:',alternativas:['a) Criação de tribunais especializados para julgamento de crimes contra o SUS','b) Processos judiciais movidos por cidadãos para garantir acesso a medicamentos, procedimentos ou internações negados pelo sistema público','c) Punição judicial de gestores que descumprem metas e indicadores do SUS','d) Regulação judicial dos planos de saúde privados pela intervenção do Judiciário na ANS','e) Fiscalização do Ministério Público sobre gastos e contratos em saúde pública'],correta:1,explicacao:'Paim et al. apontam a judicialização como desafio: cidadãos recorrem ao Judiciário para garantir direito à saúde (medicamentos de alto custo, cirurgias, internações negadas), gerando impacto no orçamento e tensões com a política de saúde coletiva.',dificuldade:'media',origem:'seed'},
  {id:'q049',temaId:'politicas-saude',categoria:'geral',enunciado:'O conceito de determinantes sociais de saúde (DSS), incorporado pelo SUS, implica que:',alternativas:['a) As doenças são resultado exclusivo de fatores biológicos e genéticos individuais','b) As condições de vida, trabalho, distribuição de renda, educação e ambiente influenciam diretamente a saúde das populações','c) A saúde é determinada apenas pelo acesso e qualidade dos serviços médico-hospitalares','d) Políticas de saúde devem focar exclusivamente na atenção curativa hospitalar de alta complexidade','e) A mortalidade é o único indicador válido para medir o impacto dos determinantes sociais'],correta:1,explicacao:'Os DSS (CNDSS/OMS) são as condições em que as pessoas nascem, crescem, vivem, trabalham e envelhecem — renda, educação, habitação, saneamento, emprego. São causas das causas das doenças e das desigualdades em saúde.',dificuldade:'media',origem:'seed'},
  {id:'q050',temaId:'politicas-saude',categoria:'geral',enunciado:'A Portaria GM/MS 4.279/2010 estabeleceu as diretrizes para a organização das Redes de Atenção à Saúde (RAS) no SUS. A RAS é definida como:',alternativas:['a) Conjunto de hospitais de alta complexidade organizados por macrorregião de saúde','b) Arranjos organizativos de ações e serviços com diferentes densidades tecnológicas, integrados por sistemas de apoio e gestão, para garantir integralidade do cuidado','c) Sistema de referência e contrarreferência exclusivo para o manejo de doenças crônicas','d) Rede formada por unidades de atenção básica que substitui hospitais de pequeno porte regionais','e) Estrutura formada apenas por serviços públicos do SUS, excluindo prestadores conveniados'],correta:1,explicacao:'Portaria 4.279/2010: RAS são arranjos organizativos de ações e serviços de diferentes densidades tecnológicas, integrados por sistemas de apoio técnico, logístico e de gestão, visando garantir a integralidade do cuidado na rede regionalizada.',dificuldade:'media',origem:'seed'},
  {id:'q051',temaId:'politicas-saude',categoria:'geral',enunciado:'Paim et al. (The Lancet, 2011) apontam que, embora o gasto total em saúde no Brasil corresponda a cerca de 8,4% do PIB, o gasto PÚBLICO representa menos de 50% desse total. Essa característica é paradoxal em sistemas universais porque:',alternativas:['a) O Brasil gasta mais em saúde em termos absolutos per capita do que os países europeus com sistemas universais','b) Em sistemas universais europeus, o gasto público costuma superar 70-80% do total, enquanto no Brasil o setor privado tem peso desproporcional apesar do caráter universal do SUS','c) O SUS é financiado exclusivamente por contribuições sociais, sem participação de impostos gerais do governo','d) A saúde suplementar brasileira é totalmente subsidiada pelo Estado, inflando artificialmente o gasto privado','e) No Brasil, os municípios respondem por 80% do financiamento do SUS, invertendo o modelo tripartite usual'],correta:1,explicacao:'Paim et al. expõem o paradoxo: o SUS é universal, mas o gasto privado supera o público (~52% vs 48%). Em sistemas universais europeus (NHS britânico, SNS espanhol), o público ultrapassa 75%. Isso reflete subfinanciamento do SUS e a dupla cobertura (SUS + planos com subsídio fiscal).',dificuldade:'dificil',origem:'seed'},
  {id:'q052',temaId:'politicas-saude',categoria:'geral',enunciado:'A transição epidemiológica no Brasil, conforme descrito por Paim et al. (2011), é caracterizada por uma situação denominada:',alternativas:['a) Substituição completa das doenças infecciosas pelas doenças crônicas não transmissíveis','b) Tripla carga de doenças: doenças infecciosas ainda prevalentes + alta mortalidade por causas externas + crescimento das DCNT','c) Eliminação das doenças negligenciadas com foco exclusivo nas DCNT e saúde mental','d) Predominância das doenças mentais como principal causa de morbimortalidade no país','e) Transição epidemiológica clássica completa, com envelhecimento acelerado e queda das doenças infecciosas'],correta:1,explicacao:'O Brasil não completou a transição epidemiológica clássica. Paim et al. descrevem uma tripla carga: ainda há doenças infecciosas (dengue, TB, leishmaniose); altíssima mortalidade por causas externas (homicídios, acidentes); e crescimento das DCNT. Isso exige que o SUS atenda três agendas simultaneamente.',dificuldade:'dificil',origem:'seed'},
  {id:'q053',temaId:'politicas-saude',categoria:'geral',enunciado:'A Resolução CNS 453/2012, sobre a composição dos Conselhos de Saúde, estabelece que os representantes de usuários devem corresponder a:',alternativas:['a) 50% do total, sendo os demais 50% divididos entre governo, prestadores e profissionais de saúde','b) 33% do total, em paridade com governo e prestadores/profissionais','c) 40% do total, com 30% de profissionais, 20% de prestadores e 10% de governo','d) 25% do total, junto com representantes de governo, prestadores e profissionais em partes iguais','e) 60% do total, garantindo maioria absoluta dos usuários nas deliberações'],correta:0,explicacao:'Lei 8.142/1990 e Resolução CNS 453/2012: paridade obrigatória — 50% de representantes de usuários e 50% dos demais (governo ~25%, prestadores de serviços ~12,5%, profissionais de saúde ~12,5%). A metade dos usuários iguala a soma de todos os demais segmentos.',dificuldade:'dificil',origem:'seed'},
  {id:'q054',temaId:'politicas-saude',categoria:'geral',enunciado:'O SUDS (Sistema Unificado e Descentralizado de Saúde), criado em 1987, foi historicamente importante porque:',alternativas:['a) Criou o SUS como sistema universal, antecipando formalmente a CF/1988','b) Constituiu experiência de transição para unificação e descentralização das ações de saúde, transferindo recursos do INAMPS para as secretarias estaduais antes da CF/1988','c) Regulamentou definitivamente a participação privada na saúde como complementar ao público','d) Extinguiu o INAMPS e criou as Secretarias Municipais de Saúde em todo o país','e) Foi responsável pela criação das Regiões de Saúde como modelo organizativo definitivo'],correta:1,explicacao:'O SUDS (Decreto 94.657/1987) foi estratégia de transição: transferiu gestão das ações de saúde do INAMPS para secretarias estaduais, criando condições políticas e técnicas para o SUS na CF/1988. Não era universal (mantinha vínculo previdenciário), mas avançou na descentralização.',dificuldade:'dificil',origem:'seed'}
];

const novosFlashcards = [
  // ---- SUS (fc031-fc033) ----
  {id:'fc031',temaId:'sus',frente:'O que é o COAP e entre quem é firmado?',verso:'Contrato Organizativo da Ação Pública da Saúde — acordo de colaboração entre entes federativos (União, estados e municípios) para organizar e integrar ações e serviços de saúde em rede regionalizada e hierarquizada. Instituído pelo Decreto 7.508/2011.',origem:'seed'},
  {id:'fc032',temaId:'sus',frente:'Quais são as condições para um município receber transferências de recursos do SUS (Lei 8.142/1990)?',verso:'Fundo de Saúde • Conselho de Saúde em funcionamento • Plano de Saúde • Relatórios de Gestão • Contrapartida de recursos • Comissão de Auditoria.',origem:'seed'},
  {id:'fc033',temaId:'sus',frente:'Qual a diferença entre RENASES e RENAME?',verso:'RENASES = Relação Nacional de Ações e Serviços de Saúde (o que o SUS oferece em serviços). RENAME = Relação Nacional de Medicamentos Essenciais (medicamentos disponíveis no SUS). Ambas instituídas pelo Decreto 7.508/2011.',origem:'seed'},
  // ---- politicas-saude (fc034-fc040) ----
  {id:'fc034',temaId:'politicas-saude',frente:'O que foi a 8ª Conferência Nacional de Saúde (1986) e qual sua importância?',verso:'Maior evento de participação popular em saúde do Brasil até então. Propôs a Reforma Sanitária e o conceito ampliado de saúde. Base política e técnica para a criação do SUS na CF/1988.',origem:'seed'},
  {id:'fc035',temaId:'politicas-saude',frente:'Cite 3 avanços e 3 desafios do SUS apontados por Paim et al. (The Lancet, 2011).',verso:'Avanços: expansão da ESF, PNI (imunização) e programa HIV/AIDS. Desafios: subfinanciamento do SUS, segmentação público-privada e judicialização da saúde.',origem:'seed'},
  {id:'fc036',temaId:'politicas-saude',frente:'O que é a "tripla carga de doenças" no Brasil?',verso:'Coexistência de: (1) doenças infecciosas/parasitárias ainda prevalentes; (2) alta mortalidade por causas externas (violência e acidentes); (3) crescimento das DCNT. O SUS precisa responder a três agendas epidemiológicas simultaneamente.',origem:'seed'},
  {id:'fc037',temaId:'politicas-saude',frente:'Qual o paradoxo do financiamento em saúde no Brasil (Paim et al., 2011)?',verso:'O SUS é universal (público), mas o gasto privado supera o público (~52% vs 48%). Em sistemas universais europeus, o gasto público ultrapassa 75%. Reflexo do subfinanciamento do SUS e da dupla cobertura (SUS + planos privados com renúncia fiscal).',origem:'seed'},
  {id:'fc038',temaId:'politicas-saude',frente:'Qual a diferença entre PACS (1991) e ESF (1994)?',verso:'PACS: agentes comunitários de saúde em visitas domiciliares, foco em vigilância e educação em saúde. ESF: equipe multiprofissional (médico, enfermeiro, técnico de enfermagem + ACS) com território adscrito e cuidado integral à família.',origem:'seed'},
  {id:'fc039',temaId:'politicas-saude',frente:'O que a Lei 10.216/2001 (Reforma Psiquiátrica) estabelece sobre internação?',verso:'Internação é último recurso, após esgotamento dos meios extra-hospitalares. Três tipos: voluntária (consentimento do paciente), involuntária (sem consentimento, com comunicação ao MP em 72h) e compulsória (determinada pela Justiça).',origem:'seed'},
  {id:'fc040',temaId:'politicas-saude',frente:'O que é a Declaração de Alma-Ata (1978) e sua relação com o SUS?',verso:'Conferência internacional (OMS/UNICEF, URSS) que propôs Atenção Primária à Saúde como eixo dos sistemas e a meta "Saúde para Todos no Ano 2000". Influenciou diretamente o movimento sanitarista brasileiro e a criação do SUS.',origem:'seed'}
];

d.questoes = d.questoes.concat(novasQuestoes);
d.flashcards = d.flashcards.concat(novosFlashcards);
fs.writeFileSync(filePath, JSON.stringify(d, null, 2), 'utf8');

const susQ = d.questoes.filter(x => x.temaId === 'sus').length;
const polQ = d.questoes.filter(x => x.temaId === 'politicas-saude').length;
const susFC = d.flashcards.filter(x => x.temaId === 'sus').length;
const polFC = d.flashcards.filter(x => x.temaId === 'politicas-saude').length;
console.log(`sus: Q=${susQ}/20 FC=${susFC}/7`);
console.log(`politicas-saude: Q=${polQ}/20 FC=${polFC}/7`);
console.log(`TOTAL Q=${d.questoes.length} FC=${d.flashcards.length}`);
